# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2026, Loan Bernat

[project]
name = "magma_core"
version = "0.1.0"
description = "Core abstractions and protocols for MAGMA"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["torch","requests","mani_skill","numpy<2.0"] 
# Numpy < 2.0 because mani_skill supports only numpy 1.x

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
